---
# comments:
#  - Заводим хост в inventory на localhost
#  - Настраиваем первичную конфигурацию (таски)
#    - Установка докера/podman
#  - Jinja2 - шаблон docker-compose
#    - 2 niginx
#    - темплейтинг из переменных host-vars.yaml и group-vars.yaml

- name: Setup containers
  gather_facts: false #Можно выстаивить глобально
  hosts: localhost #Указывать группу хостов, группа хостов должна быть завязана на некой роли
  connection: local

  roles:
    - essentials
    - compose