---
globals:
  debug: true

services: #нужны более конкретные имена, для избежания конфликтов в разных ролях
  - name: whoami_service
    image: traefik/whoami:v1.10
    expose: 80 #странное решение, указывать только один порт из пары в экспоузах
               # это порты, которые открываются внутри контейнера

  - name: apache_service
    image: httpd
    expose: 80
    traefik:
      enable: true
      http.routers.apache_service.rule: "Host(`httpd.example.com`)"
      http.services.apache_service.loadbalancer.server.port: 80
      http.routers.apache_service.entrypoints: websecure
      http.routers.apache_service.tls.certresolver: le
      http.routers.apache_service.tls: false
