---
services: #нужны более конкретные имена, для избежания конфликтов в разных ролях
  - name: whoami
    image: traefik/whoami #всегда использовать конкретные версии тега в имеджах
    expose: 80 #странное решение, указывать только один порт из пары в экспоузах

  - name: apache
    image: httpd
    expose: 80
